attr_rate: 0.1
emo_rate: 0.1
emotion: all
learnable_property: ["object","scene"]
learning_rate: 0.0001
max_train_steps: 4000
model: MLP
need_Dropout: true
need_LN: true
need_ReLU: true
num_fc_layers: 4
num_train_epochs: 1
output_dir: runs/test
pretrained_model_name_or_path: sd-legacy/stable-diffusion-v1-5
seed: 520
threshold: 0
train_data_dir: /mnt/c/Users/giann/Downloads/EmoSet-118k/